baseURL: https://frascu.github.io
languageCode: it-it
title: "Francesco Scuccimarri"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
#googleAnalytics: G-S1ZZZ6MGED

minify:
    disableXML: true
    #minifyOutput: true

# defaultContentLanguage: "it"

languages:
  en:
    languageName: ":gb:"
    weight: 2
    profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Software Engineer"
      imageUrl: "https://www.gravatar.com/avatar/416a7beaf9a43ae17bd3a27b5d0e942c?s=300" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
      #buttons:
      #  - name: Curriculum
      #    url: "/archives"
    # menu:
    #   main:
          # - identifier: home
          #   name: Home
          #   weight: 1
          # - identifier: posts
          #   name: Posts
          #   url: /posts/
          #   weight: 2
          # - identifier: categories
          #   name: Categories
          #   url: /categories/
          #   weight: 3
          # - name: Search
          #   url: /search/
          #   weight: 4
        #- identifier: tags
        #  name: Tag
        #  url: /tags/
        #- identifier: archives
        #  name: Archivio
        #  url: /archives/
  it:
    languageName: ":it:"
    languageAltTitle: Italiano
    weight: 1
    profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Software Engineer"
      imageUrl: "https://www.gravatar.com/avatar/416a7beaf9a43ae17bd3a27b5d0e942c?s=300" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
      #buttons:
      #  - name: Curriculum
      #    url: "/archives"
    # menu:
    #   main:
        # - identifier: home
        #   name: Home
        #   weight: 1
        # - identifier: posts
        #   name: Articoli
        #   url: /posts/
        #   weight: 2
        # - identifier: categorie
        #   name: Categorie
        #   url: /categories/
        #   weight: 3
        # - name: Cerca
        #   url: /search/
        #   weight: 4
        #- identifier: tags
        #  name: Tag
        #  url: /tags/
        #- identifier: archives
        #  name: Archivio
        #  url: /archives/


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Francesco Succimarri's website"
  author: "Francesco Scuccimarri"

  cookieBannerEnabled: false
  defaultTheme: dark
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: false
  #images: ["papermod-cover.png"]
  label:
    text: " " #empty

  profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Software Engineer"
      imageUrl: "https://www.gravatar.com/avatar/416a7beaf9a43ae17bd3a27b5d0e942c?s=30" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/frascu"
    - name: "github"
      url: "https://github.com/frascu"
    - name: "gitlab"
      url: "https://gitlab.com/francesco.scuccimarri"
#    - name: "stackoverflow"
#      url: "https://stackoverflow.com/users/2526969/frascu"
#    - name: "hackerrank"
#      url: "https://hackerrank.com/frascu"
#    - name: "twitter"
#      url: "https://twitter.com/frascu_dev"
    #- name: "email"
    #  url: "mailto:francesco@scuccimarri.it"
    # - name: "discord"
    #   url: "https://discordapp.com/users/750307902060888135"
#    - name: "telegram"
#      url: "https://t.me/frascu"
  assets:
    favicon: "favicon.png"
