baseURL: https://scuccimarri.it/
languageCode: en-us
title: 
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    #minifyOutput: true


languages:
  en:
    languageName: ":gb:"
    weight: 1
    profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Software Developer"
      imageUrl: "me.jpg" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
    # menu:
    #    main:
          # - identifier: home
          #   name: Home
          #   weight: 1
          # - identifier: posts
          #  name: Posts
          #  url: /posts/
          #  weight: 2
          # - identifier: categories
          #  name: Categories
          #  url: /categories/
          #  weight: 3
          # - identifier: tags
          #   name: Tags
          #   url: /tags/
          #   weight: 3
          # - identifier: archives
          #   name: Archive
          #   url: /archives/
          #   weight: 4
          # - name: Search
          #   url: /search/
          #   weight: 5
  it:
    languageName: ":it:"
    languageAltTitle: Italiano
    weight: 2
    profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Sviluppatore di Software"
      imageUrl: "me.jpg" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
    # menu:
    #   main:
    #     - identifier: home
    #       name: Home
    #       weight: 1
        # - identifier: posts
        #   name: Articoli
        #   url: /posts/
        #   weight: 2
        #- identifier: categories
        #  name: Categories
        #  url: /categories/
        #  weight: 3
        # - identifier: tags
        #   name: Tag
        #   url: /tags/
        #   weight: 3
        # - identifier: archives
        #   name: Archivio
        #   url: /archivio/
        #   weight: 4
        # - name: Cerca
        #   url: /cerca/


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Francesco Succimarri's website"
  author: "Francesco Scuccimarri"

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: false
  #images: ["papermod-cover.png"]

  profileMode:
      enabled: true
      title: "Francesco Scuccimarri" # optional default will be site title
      subtitle: "Software Developer"
      imageUrl: "me.jpg" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
      #buttons:
      #  - name: Archives
      #    url: "/archives"
      #  - name: Archive
      #    url: "/archive"
      #  - name: Github
      #    url: "https://github.com/"

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/francesco-scuccimarri/"
    - name: "github"
      url: "https://github.com/frascu"
    - name: "gitlab"
      url: "https://gitlab.com/frascu"
    - name: "email"
      url: "mailto:francesco@scuccimarri.it"
    - name: "discord"
      url: "https://discordapp.com/users/frascu#4011"

  assets:
    favicon: "favicon.png"
