baseURL: https://frascu.github.io
languageCode: it-it
#title: ""
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
#googleAnalytics: G-S1ZZZ6MGED

minify:
    disableXML: true
    #minifyOutput: true

defaultContentLanguage: "it"

languages:
  en:
    languageName: ":gb:"
    languageAltTitle: English
    weight: 2
    title: "frascu's blog"
    profileMode:
      enabled: true
      title: "frascu" # optional default will be site title
      subtitle: "Software Developer"
      imageUrl: "https://www.gravatar.com/avatar/416a7beaf9a43ae17bd3a27b5d0e942c?s=300" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
      #buttons:
      #  - name: Curriculum
      #    url: "/archives"
    menu:
      main:
        - identifier: home
          name: Home
          weight: 1
        - identifier: posts
          name: Blog
          url: /blog
          weight: 2
        - name: Search
          url: /search
          weight: 3
        #- identifier: categories
        #  name: Categories
        #  url: /categories/
        #  weight: 3
        #- identifier: tags
        #  name: Tag
        #  url: /tags/
        #- identifier: archives
        #  name: Archivio
        #  url: /archives/
  it:
    languageName: ":it:"
    languageAltTitle: Italiano
    weight: 1
    title: "Il blog di frascu"
    profileMode:
      enabled: true
      title: "frascu" # optional default will be site title
      subtitle: "Software Developer"
      imageUrl: "https://www.gravatar.com/avatar/416a7beaf9a43ae17bd3a27b5d0e942c?s=300" # optional
      imageTitle: "Immagine personale" # optional
      imageWidth: 300 # custom size
      imageHeight: 300 # custom size
      #buttons:
      #  - name: Curriculum
      #    url: "/archives"
    menu:
      main:
        - identifier: home
          name: Home
          weight: 1
        - identifier: posts
          name: Blog
          url: /blog
          weight: 2
        - name: Cerca
          url: /search
          weight: 3
        #- identifier: categorie
        #  name: Categorie
        #  url: /categories/
        #  weight: 3
        #- name: Cerca
        #  url: /search/
        #  weight: 4
        #- identifier: tags
        #  name: Tag
        #  url: /tags/
        #- identifier: archives
        #  name: Archivio
        #  url: /archives/


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "frascu's blog"
  author: "frascu"

  cookieBannerEnabled: true
  defaultTheme: dark
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: false
  #images: ["papermod-cover.png"]
  label:
    text: " " #empty

  profileMode:
    enabled: true
    title: "frascu" # optional default will be site title
    subtitle: "Software Developer"
    imageUrl: "me.jpg" # optional
    imageTitle: "Immagine personale" # optional
    imageWidth: 300 # custom size
    imageHeight: 300 # custom size

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/francesco-scuccimarri/"
    - name: "github"
      url: "https://github.com/frascu"
    - name: "gitlab"
      url: "https://gitlab.com/francesco.scuccimarri"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/2526969/frascu"
    - name: "hackerrank"
      url: "https://hackerrank.com/frascu"
    - name: "twitter"
      url: "https://twitter.com/fra_scu"
    - name: "mastodon"
      url: "https://mastodon.uno/web/@frascu"
    #- name: "email"
    #  url: "mailto:francesco@scuccimarri.it"
    # - name: "discord"
    #   url: "https://discordapp.com/users/750307902060888135"
    - name: "telegram"
      url: "https://t.me/frascu"
  assets:
    favicon: "favicon.png"
